name: Upload to Google Drive

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git sanity check
        run: |
          set -eux
          git --version
          git remote -v
          git status
          git log -1 --pretty=oneline || true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Auth via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/909118568673/locations/global/workloadIdentityPools/drive-pool/providers/github-provider
          service_account: drive-access@project-designer-476408.iam.gserviceaccount.com
          create_credentials_file: true

      - name: ADC check
        run: |
          node -e "const {GoogleAuth}=require('google-auth-library');(async()=>{const a=new GoogleAuth();const c=await a.getClient();const p=await a.getProjectId();console.log('ADC OK, project:', p)})().catch(e=>{console.error(e);process.exit(1)})"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Upload to Drive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}   # ← 到 repo Settings > Secrets 建這個
        run: node scripts/upload-to-drive.js
