name: Upload to Google Drive

on:
  push:
    branches: [ "main" ]   # 要改成別的分支也可以

permissions:
  id-token: write          # 必須：讓 GitHub 簽發 OIDC JWT
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 使用 GCP 的 Workload Identity Federation（不用金鑰）
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/909118568673/locations/global/workloadIdentityPools/drive-pool/providers/github-provider
          service_account: drive-access@project-designer-476408.iam.gserviceaccount.com
          audience: https://github.com/lisas2792-hub/designer

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      # 上傳測試檔案到 Google Drive
      - name: Upload to Drive
        run: node scripts/upload-to-drive.js