name: drive
on:
  push:
    branches: [ main ]   # 你的主分支，不是 main 就改這裡

permissions:
  contents: write        # 讓 GITHUB_TOKEN 有寫入權

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # 這裡放你原本要做的事（產生檔案、同步、更新等）
      # - run: npm ci && npm run build

      - name: Commit changes (if any)
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(ci): update artifacts [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
